const skills=['SAP BW/4HANA','Native HANA','Data Modeling','ADSO','CompositeProviders','CDS Views','Process Chains','DTP','BEx Queries','LO Cockpit','HANA Calculation Views','ABAP Routines','SQL Script','OData','Open ODS Views','Smart Data Access'];
const flow=['SAP R/3','Non-SAP / CSV','Extraction','BW/4HANA','HANA Modeling','Analytics'];
export default function Home(){return <main><nav className="nav"><a className="brand" href="#home">AA<span>.</span></a><div className="links"><a href="#about">About</a><a href="#experience">Experience</a><a href="#skills">Skills</a><a href="#contact">Contact</a></div><a className="navBtn" href="#contact">Let&apos;s connect ↗</a></nav>
<section id="home" className="hero section"><div className="heroCopy"><p className="eyebrow"><i/> SAP BW/4HANA CONSULTANT</p><h1>Turning enterprise<br/><em>data</em> into insight.</h1><p className="lead">Hi, I&apos;m <strong>Abu Anees</strong>. I work across SAP BW/4HANA and Native HANA to build reliable data models, extraction flows, reporting solutions and high-performing analytics.</p><div className="actions"><a className="primary" href="#experience">Explore my work <span>↓</span></a><a className="secondary" href="mailto:abuanees925@gmail.com">Get in touch ↗</a></div></div><div className="heroVisual"><div className="orbit orbit1"/><div className="orbit orbit2"/><div className="core"><span>BW</span><small>/4HANA</small></div><div className="node n1">DATA<br/><b>MODEL</b></div><div className="node n2">EXTRACT<br/><b>TRANSFORM</b></div><div className="node n3">ANALYZE<br/><b>INSIGHT</b></div></div></section>
<section id="about" className="section about"><div className="sectionTag">01 — ABOUT</div><div><h2>3+ years of building<br/><span>business intelligence.</span></h2><p>Results-oriented SAP Business Intelligence / Business Warehouse Consultant with experience in data modelling, extraction, reporting, performance tuning, data-load monitoring and production support.</p><p>His background includes SAP BW/4HANA, Native HANA, LSA/LSA++ architecture, HANA modelling, CDS views, process chains, transformations and enterprise reporting.</p></div></section>
<section className="architecture section"><div className="sectionTag">02 — DATA FLOW</div><h2>From source systems<br/><span>to business insight.</span></h2><div className="flow">{flow.map((x,i)=><div className="flowItem" key={x}><div>{x}</div>{i<flow.length-1&&<b>→</b>}</div>)}</div></section>
<section id="experience" className="section experience"><div className="sectionTag">03 — EXPERIENCE</div><div className="timeline"><article className="job current"><div className="date">NOV 2025 — PRESENT</div><div><div className="jobTop"><h3>Infosys</h3><span>CURRENT</span></div><h4>SAP BW/4HANA Consultant</h4><p>Working in SAP BW/4HANA consulting, applying experience across data modelling, extraction, reporting, monitoring and HANA-based analytics.</p></div></article><article className="job"><div className="date">AUG 2022 — 2025</div><div><h3>Web Synergies Pvt. Ltd.</h3><h4>SAP BW4HANA / HANA Consultant</h4><p><b>Client: YOKOGAWA</b></p><p>Worked across SAP BW data extraction, transformations and DTPs, data modelling, process-chain monitoring, HANA calculation views, ABAP routines, SQL scripts and production support.</p></div></article></div></section>
<section id="skills" className="section skills"><div className="sectionTag">04 — EXPERTISE</div><h2>Tools of the <span>trade.</span></h2><div className="skillGrid">{skills.map((s,i)=><div className="skill" key={s}><small>{String(i+1).padStart(2,'0')}</small>{s}<b>↗</b></div>)}</div></section>
<section className="section education"><div className="sectionTag">05 — EDUCATION</div><div className="eduCard"><div className="eduYear">2017</div><div><h3>Bachelor of Technology</h3><p>Mechanical Engineering</p><span>Brindavan Institute of Technology and Science</span></div></div></section>
<section id="contact" className="contact section"><p className="eyebrow"><i/> HAVE A PROJECT IN MIND?</p><h2>Let&apos;s connect<br/><em>&amp; build.</em></h2><a className="email" href="mailto:abuanees925@gmail.com">abuanees925@gmail.com ↗</a><div className="contactMeta"><span>H. Abu Anees</span><span>SAP BW/4HANA · Native HANA · SAC</span><span>India</span></div></section><footer>© {new Date().getFullYear()} Abu Anees <span>Designed for SAP data professionals.</span></footer></main>}
